RHELPLAN-68117 - Collections - Selinux - fixing ansible-test errors
RHELPLAN-56179 - Add the __future__ boilerplate to all of the modules and module_utils code

library/selogin.py
- ERROR! module fedora.linux_system_roles.selogin missing documentation
- ERROR: plugins/modules/selogin.py:0:0: missing: from __future__ import
- ERROR: plugins/modules/selogin.py:0:0: missing: __metaclass__ = type
- ERROR: plugins/modules/selogin.py:203:11: duplicate-except:
  Catching previously caught exception type OSError
- ERROR: plugins/modules/selogin.py:253:11: duplicate-except:
  Catching previously caught exception type OSError
- ERROR: plugins/modules/selogin.py:87:12: error: EXAMPLES: syntax error:
  found character '%' that cannot start any token (syntax)

plugins/modules/selinux_modules_facts.py:0:0: invalid-documentation:
- DOCUMENTATION.author: Invalid author for dictionary value @ data['author'].
  Got ['Petr Lautrbach <plautrba@redhat.com>']
- ERROR: plugins/modules/selinux_modules_facts.py:0:0: missing-examples:
  No EXAMPLES provided